# Generated by Django 5.2.7 on 2025-11-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delivered_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
